spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
<<<<<<< HEAD

=======
>>>>>>> 0cd4bfa5a4b7cb6298e2c92750fae2e6470b6978

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
